image: werockstar/android-ci:0.0.1-alpha01

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:      
  - lint
  - test
  - build
  - deploy-dev
  - deploy-uat
  - deploy-prod

linter-android:   
  stage: lint
  script:
    - ./gradlew detekt

linter-ios:   
  stage: lint
  script:
    - echo "Hello, Linter"

unit-test:   
  stage: test    
  script:
    - ./gradlew androidApp:test

build-android:
  stage: build
  script:
    - ./gradlew androidApp:assDe

deploy-dev:    
  stage: deploy-dev
  environment: dev
  script:
    - echo "Deploying application..."

deploy-uat:    
  stage: deploy-uat
  environment: uat
  script:
    - echo "Deploying application..."
  when: manual

build-uat:    
  stage: deploy-uat
  environment: uat
  needs:
    - job: deploy-uat
  script:
    - echo "Deploying application..."

release-uat:    
  stage: deploy-uat
  environment: uat
  needs:
    - job: build-uat
      artifacts: false
    - job: deploy-uat
      artifacts: false
  script:
    - echo "Deploying application..."

deploy-prod:    
  stage: deploy-prod
  environment: prod
  needs:
    - job: release-uat
  script:
    - echo "Deploying application..."
  when: manual