image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.1"
  ANDROID_SDK_TOOLS:   "9477386"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d android-sdk-linux android-sdk.zip  
  - rm android-sdk.zip 
  - mkdir android-sdk-latest; cd android-sdk-latest
  - mkdir cmdline-tools; cd cmdline-tools
  - mkdir latest
  - cd ../..
  - mv android-sdk-linux/cmdline-tools/* android-sdk-latest/cmdline-tools/latest
  - echo y | android-sdk-latest/cmdline-tools/latest/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-latest/cmdline-tools/latest/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-latest/cmdline-tools/latest/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-latest
  - export PATH=$PATH:$PWD/android-sdk-latest/platform-tools/
  - chmod +x ./gradlew
  - set +o pipefail
  - yes | android-sdk-latest/cmdline-tools/latest/bin/sdkmanager --licenses
  - set -o pipefail

stages:      
  - lint
  - test
  - build
  - deploy

lint-test-job:   
  stage: lint
  script:
    - ./gradlew detekt

unit-test-job:   
  stage: test    
  script:
    - ./gradlew androidApp:test

build-job:
  stage: build
  script:
    - ./gradlew androidApp:assDe

deploy-job:    
  stage: deploy 
  environment: production
  script:
    - echo "Deploying application..."
