image: jangrewe/gitlab-ci-android

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  ANDROID_APP: "androidApp"
  IOS_APP: "iosApp"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

.android:
  before_script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - brew install ruby
    - gem install bundler

stages:      
  - lint
  - test
  - build
  - deploy-dev
  - deploy-uat
  - deploy-prod

linter-android:   
  stage: lint
  rules:
    - changes: 
        - androidApp
  script:
    - ./gradlew detekt
  tags:
    - linux

linter-ios:   
  stage: lint
  script:
    - echo "Hello, Linter"

unit-test:   
  stage: test
  rules:
    - changes: 
        - androidApp
  script:
    - ./gradlew androidApp:test

build-android:
  stage: build
  extends: .android
  script:
    - bundle install
    - cd $ANDROID_APP
    - bundle exec fastlane lanes
    - ./gradlew assDe

deploy-dev:    
  stage: deploy-dev
  environment: dev
  script:
    - echo "Deploying application..."

deploy-uat:    
  stage: deploy-uat
  environment: uat
  script:
    - echo "Deploying application..."
  when: manual

build-uat:    
  stage: deploy-uat
  environment: uat
  needs:
    - job: deploy-uat
  script:
    - echo "Deploying application..."

release-uat:    
  stage: deploy-uat
  environment: uat
  needs:
    - job: build-uat
      artifacts: false
    - job: deploy-uat
      artifacts: false
  script:
    - echo "Deploying application..."

deploy-prod:    
  stage: deploy-prod
  environment: prod
  needs:
    - job: release-uat
  script:
    - echo "Deploying application..."
  when: manual