default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: build
        name: build ios and android
        entry: ./scripts/pre-push.sh
        language: script
        pass_filenames: false
        verbose: true
