default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: unit-test
        name: unit test
        entry: ./scripts/pre-commit.sh
        language: script
        pass_filenames: false
        verbose: true
