default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    firebase_app_distribution(
        app: "1:472674922784:android:db0687dc58fab36bb2a745",
        groups: "dev-team",
        release_notes_file: "release-notes.txt",
        service_credentials_file: "service-account-beta-deploy.json"
    )
  end

  desc "Increment Version Code"
    lane :increment_version do
      latest_release = firebase_app_distribution_get_latest_release(
        app: "1:472674922784:android:db0687dc58fab36bb2a745",
        service_credentials_file: "service-account-beta-deploy.json"
      )
      increment_version_code(
        version_code: latest_release[:buildVersion].to_i + 1,
        gradle_file_path: "androidApp/build.gradle.kts"
      )
  end

  desc "Build Android APK"
  lane :build do
    increment_version
    gradle(task: "clean androidApp:assembleDe")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
