name: Android CI
on:
  push:
    branches: [main]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: JetBrains/setup-kotlin@v1
      - run: |
            curl -L -o detekt-cli.jar https://github.com/detekt/detekt/releases/download/v1.13.0/detekt-cli-1.13.0-all.jar
      - run: | 
          java -jar detekt-cli.jar --config path/to/detekt.yml --input path/to/src --output path/to/output
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: allTests
