name: CI pipeline
on: [push]
jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest
        uses: actions/checkout@v2
      - name: JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run all tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: allTests
