name: CI pipeline
on:
  push:
    branches:
      - '**'
jobs:
  run-all-tests:
    runs-on: ubuntu-latest

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run all tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: allTests
