name: iOS CI
on:
  push:
    branches: [ main ]
    paths: [ 'shared/**', 'iosApp/**' ]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swiftlint
        run: |
          brew install swiftlint@0.50.3
      - run: make ios-linter
  unit-test:
    runs-on: macos-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.2
      - run: make ios-all-test
  build:
    runs-on: macos-latest
    needs: [ unit-test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.2
      - run: make ios-build