name: iOS CI
on:
  push:
    branches: [ main ]
    paths: [ 'shared/**', 'iosApp/**' ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.2
      - run: make ios-build