name: iOS CI
on:
  push:
    branches: [main]
jobs:
  run-all-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-xcode@v2
        with:
          xcode-version: 14.2
      - uses: actions/xcode-test@v2
        with:
          xcworkspace: iosApp.xcodeproj
          scheme: iosApp
          configuration: Debug
          sdk: iphonesimulator
          destination: 'platform=iOS,name=iPhone 14 Pro Max'